import "./globals.css";
import Nav from "@/components/Nav";
export const metadata = {
  title: "Our Blog Website",
  description: "Generated by VedaSid",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav></Nav>
      <body>{children}</body>
    </html>
  );
}
